Add Python 3.9 compatibility
jazzband/django-silk pull request #404
Opened 2020-02-24 15:44 UTC by tirkarthi

Fixes #403 #402

2020-02-24 16:02 UTC, tirkarthi commented
For some reason 3.9 only installs and exits. Maybe I am missing something in the tox configuration for 3.9 since it's in pre-release state.

2020-11-03 04:14 UTC, auvipy requested changes

2020-11-03 04:14 UTC, auvipy commented on .travis.yml
> +  - 3.9-dev
this can be 3.9 now

2020-12-05 11:43 UTC, nasirhjafri approved these changes

2020-12-05 11:43 UTC, merged