fix: DataCollector sql_queries model not found on filter(request=self…
jazzband/django-silk pull request #476
Opened 2021-06-13 10:33 UTC by jooof

Closes #475 

After digging into silk DataCollector, I figured out in the second line of this section of the code no sql query is returned. So the part where adds model to query dictionaries, can't do it's job and we face the error issued in #475 
```
models.SQLQuery.objects.bulk_create(sql_queries)
sql_queries = models.SQLQuery.objects.filter(request=self.request)
```  

By changing these 2 lines to `sql_queries = models.SQLQuery.objects.bulk_create(sql_queries)`, sql_queries is no longer empty and the rest of the system can function correctly.

2021-06-13 12:10 UTC, auvipy requested changes
can you please add a test for the changes?

2021-06-13 14:05 UTC, jooof commented
> can you please add a test for the changes?

I currently don't know exactly for what reason this issue happens. Should check it out further.

2021-09-03 23:33 UTC, Archmonger commented
Fairly insignificant code coverage change, and I don't believe tests are needed for just changing how the variable is assigned.

Will merge.

2021-09-03 23:33 UTC, merged

2021-09-03 23:55 UTC, Archmonger commented
Reverted this merge due to this issue

```
Exception when performing meta profiling, dumping trace below
Traceback (most recent call last):
  File "C:\Users\username\Documents\Repositories\Conreq-docs\.venv\lib\site-packages\silk\middleware.py", line 132, in _process_response
    collector.finalise()
  File "C:\Users\username\Documents\Repositories\Conreq-docs\.venv\lib\site-packages\silk\collector.py", line 189, in finalise
  File "C:\Users\username\Documents\Repositories\Conreq-docs\.venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 1015, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "C:\Users\username\Documents\Repositories\Conreq-docs\.venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 950, in add
    self._add_items(
  File "C:\Users\username\Documents\Repositories\Conreq-docs\.venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 1126, in _add_items
    target_ids = self._get_target_ids(target_field_name, objs)
  File "C:\Users\username\Documents\Repositories\Conreq-docs\.venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 1062, in _get_target_ids
    raise ValueError(
ValueError: Cannot add "<SQLQuery: SQLQuery object (None)>": the value for field "sqlquery" is None
```

2021-09-06 03:15 UTC, auvipy commented
you should not have merge this on the first place.

2021-09-06 07:45 UTC, Archmonger commented
I agree with you, my mistake.