Ensure sorting between most db queries requests
jazzband/django-silk pull request #484
Opened 2021-06-24 15:35 UTC by ErwinJunge

This PR ensures that the result in the "Most Database Queries" is actually sorted in descending order. The previous code could result in the results being out of order since the ordering was applied seperately per view_name.

2021-07-01 07:55 UTC, ErwinJunge commented
@auvipy could you hit the button to approve the workflow run?

2021-07-01 11:25 UTC, auvipy commented
done

2021-07-02 05:44 UTC, auvipy requested changes
can you check the build failures? also shouldn't we update unit tests for the change?

2021-07-02 09:57 UTC, ErwinJunge commented
> can you check the build failures? also shouldn't we update unit tests for the change?

The build failures aren't related to the code changes in the PR. In fact, they're also present in https://github.com/jazzband/django-silk/pull/479/checks which doesn't do any code changes at all. It looks like master is broken.

Regarding updating the unit tests: I agree, that was a bit of an oversight on my end. I'll update them asap.

2021-07-04 06:02 UTC, auvipy commented
but test needed for all the proposed changes

2021-07-08 04:40 UTC, Andrew-Chen-Wang commented
@auvipy ref: https://github.com/psycopg/psycopg2/issues/1293 looking to see if anyone else has a solution in jazz band discussion. If not, then we can merge #486

2021-08-28 11:14 UTC, auvipy approved these changes

2021-08-28 11:14 UTC, merged