Quality of life improvements in Requests tab
jazzband/django-silk pull request #537
Opened 2022-01-05 14:25 UTC by glujan

I'm using you're package quite often and wanted to give something back to this project 😄 

This PR focuses on improving experience on _Request_ tab - one improvement per commit:
*  Add message when there are no requests to display: when there are no matches instead of displaying an empty page, let user know that there are no filter results
* Add 'Clear all filters' button - when user fills in a few filters, clearing them is rather tedious task so I thought it would be nice to have a button to clear filters.
*  Add small margin for filter selects: I think this change makes filter section looks much better.

This branch is based off 4.2.0 tag because there seem to be some JS issue(s) on master branch. I also might tackle that but I think it should be in a separate PR.

2022-01-06 05:11 UTC, auvipy commented
thank your for your contributions, lets see what the CI says :D

2022-01-06 05:30 UTC, auvipy commented
can you please share the screenshots of UI that changed with this PR?

2022-01-06 09:20 UTC, glujan commented
### Updated filters:
![Filters](https://user-images.githubusercontent.com/3079032/148357985-da104347-1709-459b-a3aa-be70e7b892bc.png)

### New message saying there are no matching results:
![No matches found](https://user-images.githubusercontent.com/3079032/148358102-826f3df3-94e5-467c-b57b-44fda411d0ea.png)

### Changes not included in this PR

I also have some other changes to CSS which makes text inputs in filters easier to see (some of my colleagues did not notice that you can use filters like _Executed **n** seconds ago_). I can include those changes in the PR if you like it but of course for me it's fine to keep it as overrides in my project(s):
![obraz](https://user-images.githubusercontent.com/3079032/148358918-468b7bbf-7ce4-4092-9dd9-b6ea8762148f.png)

2022-01-06 09:41 UTC, auvipy commented
you can add the other improvements to this PR

2022-01-10 10:05 UTC, glujan commented
@auvipy I've added those additional changes, the PR is good to be reviewed now.

2022-01-10 18:53 UTC, alanjds approved these changes

2022-01-11 02:36 UTC, albertyw approved these changes
Looks good to me too.  Thanks!

2022-01-11 03:14 UTC, auvipy approved these changes

2022-01-11 03:15 UTC, auvipy commented
> This branch is based off 4.2.0 tag, please let me know if I need to rebase.

that should target main branch

2022-01-11 08:25 UTC, glujan commented
PR was already targeting master branch, but now my branch is rebased against master branch.

2022-01-11 09:04 UTC, auvipy requested changes
btw, should'nt we mention the UI changes in the docs where necessary?

2022-01-11 09:56 UTC, glujan commented
> btw, should'nt we mention the UI changes in the docs where necessary?

@auvipy I can add some docs regarding what has changed but I cannot see any section about filtering in the docs. Could you point me where I should add it?

There is also a changelog file, should I update it or will it be updated when creating a new release?

2022-02-10 10:47 UTC, glujan commented
Hi @auvipy , should I do anything more to get this merged? I'm happy to improve this PR to meet your - and the whole Jazz Band's - expectations!

2022-03-16 05:15 UTC, albertyw commented
There's some docs under https://github.com/jazzband/django-silk/tree/master/docs/ which could be updated but none of them are invalidated by this change so I'll merge this as is.

2022-03-16 05:15 UTC, albertyw commented
There's some docs under https://github.com/jazzband/django-silk/tree/master/docs/ which could be updated but none of them are invalidated by this change so I'll merge this as is.

2022-03-16 05:16 UTC, merged