Allow to generate more informative profile file name
jazzband/django-silk pull request #638
Opened 2023-01-03 20:32 UTC by k4rl85

The aim of this pull request is to generate a more informative profile file name. This would allow us to identify the endpoint that generates a profile file without the need to open it.

To avoid breaking any existent use case I set this behavior behind the setting `SILKY_PYTHON_PROFILER_EXTENDED_FILE_NAME` that by default is disabled.

If you think we can change the generated filename without worry we can simply apply this change always without the need to introduce the new settings.

2023-01-07 04:19 UTC, albertyw commented
@k4rl85 can you try rebasing this pull request to get the tests to pass?

2023-01-11 10:31 UTC, k4rl85 commented
@albertyw rebased the pr

2023-01-15 01:00 UTC, albertyw requested changes

2023-01-20 23:31 UTC, k4rl85 commented on silk/collector.py
> +            request_path = self.request.path.replace('/', '_').lstrip('_')
@albertyw I changed the logic to remove any not ASCII char and replace with `_` only `[a-z0-9_]`.

I took as limit for path name length 50.

2023-01-22 06:25 UTC, albertyw approved these changes

2023-01-22 06:49 UTC, merged