Fix when Session, Authentication or Message middlewares are not present
jazzband/django-silk pull request #667
Opened 2023-07-27 21:00 UTC by mgaligniana

2023-07-28 19:08 UTC, mgaligniana commented on silk/middleware.py
>          self.get_response = get_response
Not sure if it's the best place to do the check, but when line `self.get_response = get_response` runs the exception mentioned in the ticked is raised

2023-07-28 19:19 UTC, yoonthegoon commented
`profiling.py`, `requests.py`, and `summary.py` look good to me. 
The tests look good at a glance.

Appears to resolve the issue on the ticket. 
Hopefully Seb or someone else comes in and checks it too.

2023-07-29 08:52 UTC, albertyw approved these changes

2023-07-29 19:06 UTC, SebCorbin requested changes

2023-07-29 19:06 UTC, SebCorbin commented on silk/views/requests.py
> +        raw_filters = request.session.get(self.session_key_request_filters, {}).copy() if hasattr(request, 'session') else {}
Thanks for your work, it's a great beginning, but if I'm not mistaking, the filters are not working when selectining them. They should work if you fall back to `request.GET or request.POST` here

2023-07-29 19:08 UTC, SebCorbin requested changes

2023-07-29 19:08 UTC, SebCorbin commented on silk/views/summary.py
> +        raw_filters = request.session.get(self.filters_key, {}) if hasattr(request, 'session') else {}
And also a fallback to `request.GET or request.POST` here

2023-08-14 12:42 UTC, mgaligniana commented
@SebCorbin First, thank you for your quick responses and the pacience 🙏 

Regarding the review:

> Thanks for your work, it's a great beginning, but if I'm not mistaking, the filters are not working when selecting them. They should work if you fall back to `request.GET or request.POST` here

I followed the `session` middleware variable approach and defined a new one for the silk's filters: [silk_filters](https://github.com/jazzband/django-silk/pull/667/files#diff-c6df0dfc9a321314dc99431481a130fe2136edb8d768cf86ad19ae4d9d8f3c15R92) as a fallback.

With that and the [custom filter manager](https://github.com/jazzband/django-silk/pull/667/files#diff-a273a37c67c5442c68d569b9adbc4b6d4297254c278addae900326f5683894cdR235) we can get filters from `session` or `silk_filters` if the first one is not defined.

What do you think?

Other question: would it be worth adding selenium tests?

2023-12-13 03:42 UTC, mgaligniana commented
Hi @albertyw! Sorry to bother you, just wondering if there is something I can do to push forward the pull request. As I mentioned in my last comment, perhaps add selenium tests could give more confident to the change? Thank you!

2024-01-26 06:22 UTC, albertyw approved these changes

2024-07-17 09:55 UTC, MattyCZ commented
Hi!

Sorry to bother, but any progress on the review? We would really appreciate this feature, since it would allow us to use silk without the middleware needed. Thank you very much

2024-07-17 11:38 UTC, mgaligniana commented
Hi @MattyCZ!

This pull request was marked as part of the last release but never merged. I think we should wait.

I'm available in case of changes required!

2024-08-13 17:24 UTC, mgaligniana commented
Hi @albertyw! I just want to let you know that this PR was marked as part of the release `5.1.0` but was never merged! https://github.com/jazzband/django-silk/releases/tag/5.1.0

2024-08-15 08:03 UTC, merged